### ISSUE TITLE
Feature request: backlinks from parameter values to configurations

### ISSUE THREAD

**Issue by Yurlungur** [eschnett/SimulationIO#2]
It is very tedious to select a given configuration by name. A preferred method would be to select parameter values and find the appropriate configuration, which would be efficient with backlinks.

**Comment by eschnett** [comment]
I think the backlink is already there. It's just not output by `list` to keep the output size manageable. If you use `h5ls` to look at the file, it should be there. The Python wrappers should also be present.

**Comment by Yurlungur** [comment]
Ah, yes. I see you're right. The wrappers are there. I'll close the issue.
