### ISSUE TITLE
Vector4D tensortype

### ISSUE THREAD

**Issue by Yurlungur** [eschnett/SimulationIO#8]
convert-carpet-output in SimulationIO isn't able to handle 4-vectors such as `RADHYDRO2::u[mu]`, where mu=0..3

This causes the mu=3 case to be neglected and not read in. In the current version of simulationio, this means there's an assertion error at line 464 of `convert-carpet-output.cpp`:
`assert(tensorcomponent);`

**Comment by eschnett** [comment]
Jonah

These are declared as and should be read in as 4 independent scalars, not
as a 4-vector. (In reality, they are actually a 4-vector, but that's beside
the point here.)

I had to "correct" this (i.e. introduce a special case) to make this work.
The current version of the code does this.

Did you build your own executable, or did you get it from me? Either
git-pulling or copying a new executable should work. Alternatively, you can
add hack in a special case that makes these a scalar.

Alter-alternatively, you can hack something that turns u[0] into a scalar
and u[1...3] into a 3-vector...

-erik

On Sun, May 1, 2016 at 2:54 PM, Jonah Miller <notifications@github.com>
wrote:

> convert-carpet-output in SimulationIO isn't able to handle 4-vectors such
> as RADHYDRO2::u[mu], where mu=0..3
>
> This causes the mu=3 case to be neglected and not read in. In the current
> version of simulationio, this means there's an assertion error at line 464
> of convert-carpet-output.cpp:
> assert(tensorcomponent);
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eschnett/SimulationIO/issues/8>
>



-- 
Erik Schnetter <schnetter@gmail.com>
http://www.perimeterinstitute.ca/personal/eschnetter/

**Comment by Yurlungur** [comment]
Erk,

Ah, I see. Thanks. I was using a version that was about a week old. Updating it included your fix.
